export const PATH_PARAM_PLACEHOLDER = '%s';

const PATHS = {
  MASSAGES: 'massages',
  PLACEHOLDER: '%s',
};

export const ENDPOINTS = {
  MASSAGES: PATHS.MASSAGES,
  MASSAGES_DETAIL: [PATHS.MASSAGES, PATH_PARAM_PLACEHOLDER].join('/'),
  MASSAGES_EDIT: [PATHS.MASSAGES, PATH_PARAM_PLACEHOLDER].join('/'),
};
